# Defines how the Secrets Store CSI driver should fetch credentials from AWS.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "my-application.fullname" . }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.database.secretArn }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
  
  # This section tells the driver to create a native Kubernetes Secret.
  # The application deployment will reference this native secret.
  secretObjects:
    - secretName: {{ include "my-application.fullname" . }}-db-creds
      type: Opaque
      data:
        - objectName: "username"
          key: "username"
        - objectName: "password"
          key: "password"
