# Creates a ServiceAccount for the application pods.
# This ServiceAccount is annotated with the IAM role that can access the secret.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-application.fullname" . }}
  labels:
    {{- include "my-application.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
